version: '3.1'

services:
  audio_hunter_bot:
    container_name: audio_hunter_bot
    environment:
      BOT_TOKEN: "your_bot_token"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always